'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccionesCorrectivas

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ASPxCallback1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxCallback1 As Global.DevExpress.Web.ASPxCallback.ASPxCallback

    '''<summary>
    '''LoadingPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoadingPanel As Global.DevExpress.Web.ASPxLoadingPanel.ASPxLoadingPanel

    '''<summary>
    '''lbltitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltitulo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblFor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFor As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblFechaTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaTitulo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFecha As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblHoraTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHoraTitulo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblHora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHora As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''ProcesosReportan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProcesosReportan As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''PageControlIngresos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageControlIngresos As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''FormLayoutIngresando control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormLayoutIngresando As Global.DevExpress.Web.ASPxFormLayout.ASPxFormLayout

    '''<summary>
    '''lblCedula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCedula As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtCedula control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCedula As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblespcio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblespcio As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''btnBuscarSolicitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscarSolicitante As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblInfor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInfor As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombre As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblNombreIngresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreIngresa As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblCorreIngresa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorreIngresa As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblCorreoUsuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorreoUsuario As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''FormLayoutIngresoDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormLayoutIngresoDatos As Global.DevExpress.Web.ASPxFormLayout.ASPxFormLayout

    '''<summary>
    '''lblSolictante1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolictante1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtSolicitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolicitante As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorreo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''txtCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreo As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''lblCargo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCargo1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''comboCargo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents comboCargo As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Cargos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cargos As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblFechaReporteTitulo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaReporteTitulo1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblFechaReporte1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaReporte1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblfechaIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfechaIdentificacion As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''DateEditIdentificaicon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateEditIdentificaicon1 As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''lblproceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblproceso As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProceso As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''btnSiguiente1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSiguiente1 As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblTitulo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones4 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones5 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones6 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones7 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones8 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblIndicaciones9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIndicaciones9 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblTipoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoAccion As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbTipoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoAccion As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''TipoAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TipoAccion As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblFuenteInformacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuenteInformacion As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbTipoInformacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoInformacion As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''FuenteInfor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FuenteInfor As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblSiglasAuditorias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiglasAuditorias As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbSiglasAuditorias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSiglasAuditorias As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Siglas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Siglas As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNovedad As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmbNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNovedad As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Novedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Novedad As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblTitulo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitulo2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lblDescripcionMejora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDescripcionMejora As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''MemoDescripcionMejora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MemoDescripcionMejora As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''btnGenerarAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerarAccion As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetalle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''FormLayoutEvidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FormLayoutEvidencia As Global.DevExpress.Web.ASPxFormLayout.ASPxFormLayout

    '''<summary>
    '''RadioButtonTipoIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonTipoIngreso As Global.DevExpress.Web.ASPxEditors.ASPxRadioButtonList

    '''<summary>
    '''memoDetalleEvidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoDetalleEvidencia As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''btnFinalizarAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinalizarAccion As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''PopupControleError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControleError As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl7 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''lblComunicado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComunicado As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''PopupControlIngresoExitoso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlIngresoExitoso As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl

    '''<summary>
    '''PopupControlContentControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlContentControl1 As Global.DevExpress.Web.ASPxPopupControl.PopupControlContentControl

    '''<summary>
    '''ASPxLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxLabel1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''btnSalir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalir As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''PopupControlEvidenciasFisicas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopupControlEvidenciasFisicas As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl
End Class
