<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="DetalleEvidencias.aspx.vb" Inherits="AccionesCorrectivas.DetalleEvidencias" %>

<%@ Register Assembly="DevExpress.Web.v14.1, Version=14.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web.ASPxImageSlider" TagPrefix="dx" %>

<%@ Register Assembly="DevExpress.Web.v14.1, Version=14.1.4.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" Namespace="DevExpress.Web.ASPxEditors" TagPrefix="dx" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <center>
        <table>
            <tr>
                <td>
                    <br />
                    <br />
                    &nbsp;</td>
                <td style="text-align:center ">
                    <br />
                    <br />
                    <br />
                    <dx:ASPxLabel ID="lblTitulo" runat="server" Text="SISTEMA DE GESTIÓN DE CALIDAD" Font-Bold="True" Font-Italic="False" Font-Size="X-Large"></dx:ASPxLabel>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <br />
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <br />
                    <dx:ASPxImage ID="ImageAccionCorrectiva" runat="server" ShowLoadingImage="true" ImageUrl= "~/Imagenes/EvidenciasAcciones.png" Width="100%"></dx:ASPxImage>
                    <br />
                    <br />
                    <br />
                    <br />
                </td>
            </tr>
            <%--<tr>
                <td>
                    <asp:LinkButton ID="btnDescargar" runat="server" Text="DESCARGAR" ImageUrl="~/Imagenes/error.png" OnClick= "btnDescargar_Click"></asp:LinkButton>
                </td>
            </tr>--%>
        </table>
    </center>





         <dx:ASPxImageSlider ID="imageSlider" runat="server" 
       DataMember="DefaultView" Width="100%" Height="800px">
             <SettingsNavigationBar Position="Right" />
<SettingsAutoGeneratedImages ImageHeight="440px"></SettingsAutoGeneratedImages>

             <BorderRight BorderColor="Red" BorderStyle="Solid" />
           
        </dx:ASPxImageSlider>
                
    </div>
    </form>
</body>
</html>
